### ISSUE TITLE
Item file locations

### ISSUE THREAD

**Issue by TealcOneill** [nornagon/cdda-guide#61] opened 2022-02-18 22:09 UTC
HHG makes a great tool to glance at when coding, especially for new contributors to CDDA like myself. I often find myself searching items I'm looking to change or work with up on HGG instead of looking for it in the files just to get quick look at the item's code. If possible it would be awesome to have the file path listed right above the 'Raw Json' button as that would save a lot of time spent searching through files with other programs. Thanks for all the hard work on HHG, it's super useful!

Like this v.
![filepath](https://user-images.githubusercontent.com/45678006/154767853-d0a34b63-83be-4a63-b9b0-9c81a3b93944.png)

**Comment by nornagon** [comment] 2022-02-21 00:00
Duplicate of #55

**Closed by nornagon** 2022-02-21 00:00 UTC
