### ISSUE TITLE
Unable to See Certain Locations Within Hitch-HIker's Guide Website

### ISSUE THREAD

**Issue by coyo7e** [nornagon/cdda-guide#54] opened 2022-01-26 20:26 UTC
I really love this site and use it all the time however, I noticed that some (newer?) locations  do not seem to show up on the site, despite it seeming to scan from the game's database of locations.

For instance, the Trans Coast Logistics lab does not appear at all in drop rates. Probably a few more as well however, this can lead to significant holes in loot table searches and similar.

**Comment by nornagon** [comment] 2022-01-26 21:29
The Guide currently only shows locations that are visible on the Z=0 map, which I think doesn't include the Trans Coast Logistics lab. Additionally, we [hide some locations](https://github.com/nornagon/cdda-guide/blob/0a843a690a87d745d5222d251c44728bdbe3eb38/src/types/item/spawnLocations.ts#L176-L183) for various reasons.

**Comment by coyo7e** [comment] 2022-01-26 22:02
Oh thank you for the quick response! I always wished there was a way to search specific locations anyway so my desire may be against the overall intention of the site.

**Comment by nornagon** [comment] 2022-01-26 22:03
Searching locations is vaguely on the to-do list, and we'd probably support those "hidden" locations in that search: https://github.com/nornagon/cdda-guide/issues/33

Closing this for now as I think this is "working as intended" :)

**Closed by nornagon** 2022-01-26 22:03 UTC
