### ISSUE TITLE
Misnamed items

### ISSUE THREAD

**Issue by TealcOneill** [nornagon/cdda-guide#24] opened 2021-08-04 03:48 UTC
Sticks are now stout branches and have the description, "A respectable length of tree branch, just big enough to wrap your hand around. Makes a decent melee weapon."
Long sticks are now long stout branches and have the description, "A straight section of wood from a tree branch, about eight feet long and a couple of inches in diameter.  Makes a decent melee weapon, and can be broken into shorter pieces for crafting."
Both, bundles of stout branches and bundles of long stout branches use the antiquated name in their disassembly list.

**Comment by nornagon** [comment] 2021-08-13 01:53
Hm, this doesn't seem to be accurate? The stick item is named "stick": https://github.com/CleverRaven/Cataclysm-DDA/blob/0f8bd786da742b2e57def98e795a3a76921a30ac/data/json/items/resources/wood.json#L42

What version of the game are you seeing "stout branch" in?

**Comment by nornagon** [comment] 2021-08-13 02:03
This also seems to be the in-game name of the item, so I don't think I'm missing any renaming mechanic here. 
![image](https://user-images.githubusercontent.com/172800/129294630-bcaa3cfc-1700-4081-af88-643289f2fab7.png)

**Comment by TealcOneill** [comment] 2021-08-13 04:42
It was changed to stout branch for the 0.F stable but someone else changed it back soon after. The hhg has bundles of branches so I was going off of that. I also didn't realize that the hgg is based on the latest experimental.

**Comment by nornagon** [comment] 2021-08-13 05:07
Ok, thanks for confirming! Sounds like things are working as intended, so I'm going to close this out.

**Closed by nornagon** 2021-08-13 05:07 UTC
