### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by Abstrusle** [nornagon/cdda-guide#124] opened 2023-03-07 15:54 UTC
Entering the website once does not persist the data, likely a result of my Firefox settings. However, the source code does not contain instructions as to how the user can set-up the frontend locally, and guarantee this occurs. How do I compile the project myself? Requesting a document or an appendage to the README for Linux compilation.

**Comment by nornagon** [comment] 2023-03-07 16:05
Duplicate of #105.

Further, I'm not sure why it would be different for you setting up the frontend locally vs using it from GitHub. The "app" is just static HTML and JS files, so presumably your Firefox would forget the data no matter where it was pulling the HTML from.

**Closed by nornagon** 2023-03-07 16:05 UTC
