### ISSUE TITLE
Selecting a version causes the application to break

### ISSUE THREAD

**Issue by JamesDBowen** [nornagon/cdda-guide#177] opened 2024-07-23 13:26 UTC
Selecting a version on the main page causes the entire HHG to break.

Using the example of 0.G:
This results in this console error in chrome dev tools:
"Uncaught SyntaxError: Unexpected end of input (at index-7d695ff5.js:103:65011)"

 
There are no network errors - all requests come back with a good status.

The steps to reproduce are simple -- just select a version, and voila! It's broken. This seems to persist, as well -- even if I remove the query params specifying a version, it stays broken until I do a hard refresh.

**Comment by nornagon** [comment] 2024-07-26 21:46
Hm, I can't reproduce this. It sounds like the app might have gotten into a bad state on your machine somehow, can you try clearing all site data and trying again?

**Comment by nornagon** [comment] 2024-07-29 13:37
I'm going to close this for now, let me know if you get any further details! Would also be good to know your browser version if this persists.

**Closed by nornagon** 2024-07-29 13:37 UTC
