### ISSUE TITLE
Translations support

### ISSUE THREAD

**Issue by Faalagorn** [nornagon/cdda-guide#64] opened 2022-03-21 19:18 UTC
Hi! I'm translating the game to Polish, we're at 100% completion for master on par with several other languages (Japanese, Chinese, Spanish, Russian…) but there are some incomplete ones currently on progress, all of it can be seen in the Transifex: https://www.transifex.com/cataclysm-dda-translators/cataclysm-dda/dashboard/

The files are distributed on .po files which can be downloaded directly from Transifex the moment the strings are updated (opposite happens whenever strings in game are updated), but are also periodically imported back to the main repo each week as po files.

Would it be possible to add names from translation to the website? Possibly similar to how changing sprites work. It would be nice to see the translated items for languages that have the translations at glance, outside the debug menu, and to find them without changing the website.

I'll gladly offer Polish translation for the actual website content, too, if needed. :)

**Comment by nornagon** [comment] 2022-03-29 18:49
Duplicate of #42

**Closed by nornagon** 2022-03-29 18:49 UTC
