### ISSUE TITLE
[Feature request] Vanilla-included mods support

### ISSUE THREAD

**Issue by ThePainkiller** [nornagon/cdda-guide#156] opened 2023-10-28 10:47 UTC
It would be pretty nice if the guide included additional recipes from mods included in base game like Innawood, Aftershock and Blaze Industries or XEDRA evolved. Maybe as a separate crafting category.

**Comment by nornagon** [comment] 2023-10-28 13:36
Duplicate of #36

**Closed by nornagon** 2023-10-28 13:36 UTC
